export {default as fr} from './fr.svg';
export {default as en} from './en.svg';
export {default as es} from './es.svg';
export {default as pt} from './pt.svg';
export {default as id} from './id.svg';
export {default as de} from './de.svg';
export {default as th} from './th.svg';
export {default as pl} from './pl.svg';
export {default as zh_Hans} from './cn.svg';